import { type PrismaClient } from '../../generated/client/client'

/**
 * Parse GDPR status string and expand hierarchically
 * EU implies EEA, EEA implies EFTA
 * Adequacy decisions are parsed from strings like "Third Country (Adequate)"
 */
function parseGdprStatus(status: string): string[] {
  const result: string[] = []

  if (status.includes('EU')) {
    result.push('EU', 'EEA')
  } else if (status.includes('EEA')) {
    result.push('EEA')
  }

  if (status.includes('EFTA') && !result.includes('EEA')) {
    result.push('EFTA')
  }

  if (status.includes('Third Country')) {
    result.push('Third Country')
  }

  if (status.includes('Adequate')) {
    result.push('Adequate')
  }

  return result.length > 0 ? result : ['Third Country']
}

export async function seedCountries(prisma: PrismaClient) {
  // Check if countries already exist
  const existingCount = await prisma.country.count()
  if (existingCount > 0) {
    console.log(`Skipping countries seed - ${existingCount} countries already exist`)
    return existingCount
  }

  // Country data: [name, isoCode, isoCode3, gdprStatusString, description]
  const countriesData: [string, string, string, string, string?][] = [
    // EU Countries (27)
    ['Austria', 'AT', 'AUT', 'EU', 'Member of the European Union'],
    ['Belgium', 'BE', 'BEL', 'EU', 'Member of the European Union'],
    ['Bulgaria', 'BG', 'BGR', 'EU', 'Member of the European Union'],
    ['Croatia', 'HR', 'HRV', 'EU', 'Member of the European Union'],
    ['Cyprus', 'CY', 'CYP', 'EU', 'Member of the European Union'],
    ['Czech Republic', 'CZ', 'CZE', 'EU', 'Member of the European Union'],
    ['Denmark', 'DK', 'DNK', 'EU', 'Member of the European Union'],
    ['Estonia', 'EE', 'EST', 'EU', 'Member of the European Union'],
    ['Finland', 'FI', 'FIN', 'EU', 'Member of the European Union'],
    ['France', 'FR', 'FRA', 'EU', 'Member of the European Union'],
    ['Germany', 'DE', 'DEU', 'EU', 'Member of the European Union'],
    ['Greece', 'GR', 'GRC', 'EU', 'Member of the European Union'],
    ['Hungary', 'HU', 'HUN', 'EU', 'Member of the European Union'],
    ['Ireland', 'IE', 'IRL', 'EU', 'Member of the European Union'],
    ['Italy', 'IT', 'ITA', 'EU', 'Member of the European Union'],
    ['Latvia', 'LV', 'LVA', 'EU', 'Member of the European Union'],
    ['Lithuania', 'LT', 'LTU', 'EU', 'Member of the European Union'],
    ['Luxembourg', 'LU', 'LUX', 'EU', 'Member of the European Union'],
    ['Malta', 'MT', 'MLT', 'EU', 'Member of the European Union'],
    ['Netherlands', 'NL', 'NLD', 'EU', 'Member of the European Union'],
    ['Poland', 'PL', 'POL', 'EU', 'Member of the European Union'],
    ['Portugal', 'PT', 'PRT', 'EU', 'Member of the European Union'],
    ['Romania', 'RO', 'ROU', 'EU', 'Member of the European Union'],
    ['Slovakia', 'SK', 'SVK', 'EU', 'Member of the European Union'],
    ['Slovenia', 'SI', 'SVN', 'EU', 'Member of the European Union'],
    ['Spain', 'ES', 'ESP', 'EU', 'Member of the European Union'],
    ['Sweden', 'SE', 'SWE', 'EU', 'Member of the European Union'],

    // EEA Countries (non-EU)
    ['Iceland', 'IS', 'ISL', 'EEA', 'European Economic Area member'],
    ['Liechtenstein', 'LI', 'LIE', 'EEA', 'European Economic Area member'],
    ['Norway', 'NO', 'NOR', 'EEA', 'European Economic Area member'],

    // Countries with Adequacy Decisions
    ['Andorra', 'AD', 'AND', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Argentina', 'AR', 'ARG', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    [
      'Canada',
      'CA',
      'CAN',
      'Third Country (Adequate)',
      'GDPR adequacy decision (commercial organizations)',
    ],
    ['Faroe Islands', 'FO', 'FRO', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Guernsey', 'GG', 'GGY', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Israel', 'IL', 'ISR', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Isle of Man', 'IM', 'IMN', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Japan', 'JP', 'JPN', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Jersey', 'JE', 'JEY', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['New Zealand', 'NZ', 'NZL', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Republic of Korea', 'KR', 'KOR', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Switzerland', 'CH', 'CHE', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['United Kingdom', 'GB', 'GBR', 'Third Country (Adequate)', 'GDPR adequacy decision'],
    ['Uruguay', 'UY', 'URY', 'Third Country (Adequate)', 'GDPR adequacy decision'],

    // Major Third Countries (no adequacy decision)
    ['United States', 'US', 'USA', 'Third Country', 'No adequacy decision'],
    ['China', 'CN', 'CHN', 'Third Country', 'No adequacy decision'],
    ['India', 'IN', 'IND', 'Third Country', 'No adequacy decision'],
    ['Brazil', 'BR', 'BRA', 'Third Country', 'No adequacy decision'],
    ['Russia', 'RU', 'RUS', 'Third Country', 'No adequacy decision'],
    ['Australia', 'AU', 'AUS', 'Third Country', 'No adequacy decision'],
    ['Mexico', 'MX', 'MEX', 'Third Country', 'No adequacy decision'],
    ['South Africa', 'ZA', 'ZAF', 'Third Country', 'No adequacy decision'],
    ['Turkey', 'TR', 'TUR', 'Third Country', 'No adequacy decision'],
    ['Indonesia', 'ID', 'IDN', 'Third Country', 'No adequacy decision'],
    ['Saudi Arabia', 'SA', 'SAU', 'Third Country', 'No adequacy decision'],
    ['United Arab Emirates', 'AE', 'ARE', 'Third Country', 'No adequacy decision'],
    ['Singapore', 'SG', 'SGP', 'Third Country', 'No adequacy decision'],
    ['Malaysia', 'MY', 'MYS', 'Third Country', 'No adequacy decision'],
    ['Thailand', 'TH', 'THA', 'Third Country', 'No adequacy decision'],
    ['Vietnam', 'VN', 'VNM', 'Third Country', 'No adequacy decision'],
    ['Philippines', 'PH', 'PHL', 'Third Country', 'No adequacy decision'],
    ['Egypt', 'EG', 'EGY', 'Third Country', 'No adequacy decision'],
    ['Nigeria', 'NG', 'NGA', 'Third Country', 'No adequacy decision'],
    ['Kenya', 'KE', 'KEN', 'Third Country', 'No adequacy decision'],
    ['Chile', 'CL', 'CHL', 'Third Country', 'No adequacy decision'],
    ['Colombia', 'CO', 'COL', 'Third Country', 'No adequacy decision'],
    ['Peru', 'PE', 'PER', 'Third Country', 'No adequacy decision'],
    ['Pakistan', 'PK', 'PAK', 'Third Country', 'No adequacy decision'],
    ['Bangladesh', 'BD', 'BGD', 'Third Country', 'No adequacy decision'],

    // Additional countries for comprehensive coverage
    ['Afghanistan', 'AF', 'AFG', 'Third Country'],
    ['Albania', 'AL', 'ALB', 'Third Country'],
    ['Algeria', 'DZ', 'DZA', 'Third Country'],
    ['American Samoa', 'AS', 'ASM', 'Third Country'],
    ['Angola', 'AO', 'AGO', 'Third Country'],
    ['Anguilla', 'AI', 'AIA', 'Third Country'],
    ['Antarctica', 'AQ', 'ATA', 'Third Country'],
    ['Antigua and Barbuda', 'AG', 'ATG', 'Third Country'],
    ['Armenia', 'AM', 'ARM', 'Third Country'],
    ['Aruba', 'AW', 'ABW', 'Third Country'],
    ['Azerbaijan', 'AZ', 'AZE', 'Third Country'],
    ['Bahamas', 'BS', 'BHS', 'Third Country'],
    ['Bahrain', 'BH', 'BHR', 'Third Country'],
    ['Barbados', 'BB', 'BRB', 'Third Country'],
    ['Belarus', 'BY', 'BLR', 'Third Country'],
    ['Belize', 'BZ', 'BLZ', 'Third Country'],
    ['Benin', 'BJ', 'BEN', 'Third Country'],
    ['Bermuda', 'BM', 'BMU', 'Third Country'],
    ['Bhutan', 'BT', 'BTN', 'Third Country'],
    ['Bolivia', 'BO', 'BOL', 'Third Country'],
    ['Bosnia and Herzegovina', 'BA', 'BIH', 'Third Country'],
    ['Botswana', 'BW', 'BWA', 'Third Country'],
    ['Bouvet Island', 'BV', 'BVT', 'Third Country'],
    ['British Indian Ocean Territory', 'IO', 'IOT', 'Third Country'],
    ['Brunei', 'BN', 'BRN', 'Third Country'],
    ['Burkina Faso', 'BF', 'BFA', 'Third Country'],
    ['Burundi', 'BI', 'BDI', 'Third Country'],
    ['Cambodia', 'KH', 'KHM', 'Third Country'],
    ['Cameroon', 'CM', 'CMR', 'Third Country'],
    ['Cape Verde', 'CV', 'CPV', 'Third Country'],
    ['Cayman Islands', 'KY', 'CYM', 'Third Country'],
    ['Central African Republic', 'CF', 'CAF', 'Third Country'],
    ['Chad', 'TD', 'TCD', 'Third Country'],
    ['Christmas Island', 'CX', 'CXR', 'Third Country'],
    ['Cocos Islands', 'CC', 'CCK', 'Third Country'],
    ['Comoros', 'KM', 'COM', 'Third Country'],
    ['Congo', 'CG', 'COG', 'Third Country'],
    ['Congo (Democratic Republic)', 'CD', 'COD', 'Third Country'],
    ['Cook Islands', 'CK', 'COK', 'Third Country'],
    ['Costa Rica', 'CR', 'CRI', 'Third Country'],
    ["Côte d'Ivoire", 'CI', 'CIV', 'Third Country'],
    ['Cuba', 'CU', 'CUB', 'Third Country'],
    ['Curaçao', 'CW', 'CUW', 'Third Country'],
    ['Djibouti', 'DJ', 'DJI', 'Third Country'],
    ['Dominica', 'DM', 'DMA', 'Third Country'],
    ['Dominican Republic', 'DO', 'DOM', 'Third Country'],
    ['Ecuador', 'EC', 'ECU', 'Third Country'],
    ['El Salvador', 'SV', 'SLV', 'Third Country'],
    ['Equatorial Guinea', 'GQ', 'GNQ', 'Third Country'],
    ['Eritrea', 'ER', 'ERI', 'Third Country'],
    ['Eswatini', 'SZ', 'SWZ', 'Third Country'],
    ['Ethiopia', 'ET', 'ETH', 'Third Country'],
    ['Falkland Islands', 'FK', 'FLK', 'Third Country'],
    ['Fiji', 'FJ', 'FJI', 'Third Country'],
    ['French Guiana', 'GF', 'GUF', 'Third Country'],
    ['French Polynesia', 'PF', 'PYF', 'Third Country'],
    ['French Southern Territories', 'TF', 'ATF', 'Third Country'],
    ['Gabon', 'GA', 'GAB', 'Third Country'],
    ['Gambia', 'GM', 'GMB', 'Third Country'],
    ['Georgia', 'GE', 'GEO', 'Third Country'],
    ['Ghana', 'GH', 'GHA', 'Third Country'],
    ['Gibraltar', 'GI', 'GIB', 'Third Country'],
    ['Greenland', 'GL', 'GRL', 'Third Country'],
    ['Grenada', 'GD', 'GRD', 'Third Country'],
    ['Guadeloupe', 'GP', 'GLP', 'Third Country'],
    ['Guam', 'GU', 'GUM', 'Third Country'],
    ['Guatemala', 'GT', 'GTM', 'Third Country'],
    ['Guinea', 'GN', 'GIN', 'Third Country'],
    ['Guinea-Bissau', 'GW', 'GNB', 'Third Country'],
    ['Guyana', 'GY', 'GUY', 'Third Country'],
    ['Haiti', 'HT', 'HTI', 'Third Country'],
    ['Heard Island and McDonald Islands', 'HM', 'HMD', 'Third Country'],
    ['Honduras', 'HN', 'HND', 'Third Country'],
    ['Hong Kong', 'HK', 'HKG', 'Third Country'],
    ['Iran', 'IR', 'IRN', 'Third Country'],
    ['Iraq', 'IQ', 'IRQ', 'Third Country'],
    ['Jamaica', 'JM', 'JAM', 'Third Country'],
    ['Jordan', 'JO', 'JOR', 'Third Country'],
    ['Kazakhstan', 'KZ', 'KAZ', 'Third Country'],
    ['Kiribati', 'KI', 'KIR', 'Third Country'],
    ['Kosovo', 'XK', 'XKX', 'Third Country'],
    ['Kuwait', 'KW', 'KWT', 'Third Country'],
    ['Kyrgyzstan', 'KG', 'KGZ', 'Third Country'],
    ['Laos', 'LA', 'LAO', 'Third Country'],
    ['Lebanon', 'LB', 'LBN', 'Third Country'],
    ['Lesotho', 'LS', 'LSO', 'Third Country'],
    ['Liberia', 'LR', 'LBR', 'Third Country'],
    ['Libya', 'LY', 'LBY', 'Third Country'],
    ['Macao', 'MO', 'MAC', 'Third Country'],
    ['Madagascar', 'MG', 'MDG', 'Third Country'],
    ['Malawi', 'MW', 'MWI', 'Third Country'],
    ['Maldives', 'MV', 'MDV', 'Third Country'],
    ['Mali', 'ML', 'MLI', 'Third Country'],
    ['Marshall Islands', 'MH', 'MHL', 'Third Country'],
    ['Martinique', 'MQ', 'MTQ', 'Third Country'],
    ['Mauritania', 'MR', 'MRT', 'Third Country'],
    ['Mauritius', 'MU', 'MUS', 'Third Country'],
    ['Mayotte', 'YT', 'MYT', 'Third Country'],
    ['Micronesia', 'FM', 'FSM', 'Third Country'],
    ['Moldova', 'MD', 'MDA', 'Third Country'],
    ['Monaco', 'MC', 'MCO', 'Third Country'],
    ['Mongolia', 'MN', 'MNG', 'Third Country'],
    ['Montenegro', 'ME', 'MNE', 'Third Country'],
    ['Montserrat', 'MS', 'MSR', 'Third Country'],
    ['Morocco', 'MA', 'MAR', 'Third Country'],
    ['Mozambique', 'MZ', 'MOZ', 'Third Country'],
    ['Myanmar', 'MM', 'MMR', 'Third Country'],
    ['Namibia', 'NA', 'NAM', 'Third Country'],
    ['Nauru', 'NR', 'NRU', 'Third Country'],
    ['Nepal', 'NP', 'NPL', 'Third Country'],
    ['New Caledonia', 'NC', 'NCL', 'Third Country'],
    ['Nicaragua', 'NI', 'NIC', 'Third Country'],
    ['Niger', 'NE', 'NER', 'Third Country'],
    ['Niue', 'NU', 'NIU', 'Third Country'],
    ['Norfolk Island', 'NF', 'NFK', 'Third Country'],
    ['North Korea', 'KP', 'PRK', 'Third Country'],
    ['North Macedonia', 'MK', 'MKD', 'Third Country'],
    ['Northern Mariana Islands', 'MP', 'MNP', 'Third Country'],
    ['Oman', 'OM', 'OMN', 'Third Country'],
    ['Palau', 'PW', 'PLW', 'Third Country'],
    ['Palestine', 'PS', 'PSE', 'Third Country'],
    ['Panama', 'PA', 'PAN', 'Third Country'],
    ['Papua New Guinea', 'PG', 'PNG', 'Third Country'],
    ['Paraguay', 'PY', 'PRY', 'Third Country'],
    ['Pitcairn Islands', 'PN', 'PCN', 'Third Country'],
    ['Puerto Rico', 'PR', 'PRI', 'Third Country'],
    ['Qatar', 'QA', 'QAT', 'Third Country'],
    ['Réunion', 'RE', 'REU', 'Third Country'],
    ['Rwanda', 'RW', 'RWA', 'Third Country'],
    ['Saint Barthélemy', 'BL', 'BLM', 'Third Country'],
    ['Saint Helena', 'SH', 'SHN', 'Third Country'],
    ['Saint Kitts and Nevis', 'KN', 'KNA', 'Third Country'],
    ['Saint Lucia', 'LC', 'LCA', 'Third Country'],
    ['Saint Martin', 'MF', 'MAF', 'Third Country'],
    ['Saint Pierre and Miquelon', 'PM', 'SPM', 'Third Country'],
    ['Saint Vincent and the Grenadines', 'VC', 'VCT', 'Third Country'],
    ['Samoa', 'WS', 'WSM', 'Third Country'],
    ['San Marino', 'SM', 'SMR', 'Third Country'],
    ['São Tomé and Príncipe', 'ST', 'STP', 'Third Country'],
    ['Senegal', 'SN', 'SEN', 'Third Country'],
    ['Serbia', 'RS', 'SRB', 'Third Country'],
    ['Seychelles', 'SC', 'SYC', 'Third Country'],
    ['Sierra Leone', 'SL', 'SLE', 'Third Country'],
    ['Sint Maarten', 'SX', 'SXM', 'Third Country'],
    ['Solomon Islands', 'SB', 'SLB', 'Third Country'],
    ['Somalia', 'SO', 'SOM', 'Third Country'],
    ['South Georgia and South Sandwich Islands', 'GS', 'SGS', 'Third Country'],
    ['South Sudan', 'SS', 'SSD', 'Third Country'],
    ['Sri Lanka', 'LK', 'LKA', 'Third Country'],
    ['Sudan', 'SD', 'SDN', 'Third Country'],
    ['Suriname', 'SR', 'SUR', 'Third Country'],
    ['Svalbard and Jan Mayen', 'SJ', 'SJM', 'Third Country'],
    ['Syria', 'SY', 'SYR', 'Third Country'],
    ['Taiwan', 'TW', 'TWN', 'Third Country'],
    ['Tajikistan', 'TJ', 'TJK', 'Third Country'],
    ['Tanzania', 'TZ', 'TZA', 'Third Country'],
    ['Timor-Leste', 'TL', 'TLS', 'Third Country'],
    ['Togo', 'TG', 'TGO', 'Third Country'],
    ['Tokelau', 'TK', 'TKL', 'Third Country'],
    ['Tonga', 'TO', 'TON', 'Third Country'],
    ['Trinidad and Tobago', 'TT', 'TTO', 'Third Country'],
    ['Tunisia', 'TN', 'TUN', 'Third Country'],
    ['Turkmenistan', 'TM', 'TKM', 'Third Country'],
    ['Turks and Caicos Islands', 'TC', 'TCA', 'Third Country'],
    ['Tuvalu', 'TV', 'TUV', 'Third Country'],
    ['Uganda', 'UG', 'UGA', 'Third Country'],
    ['Ukraine', 'UA', 'UKR', 'Third Country'],
    ['United States Minor Outlying Islands', 'UM', 'UMI', 'Third Country'],
    ['Uzbekistan', 'UZ', 'UZB', 'Third Country'],
    ['Vanuatu', 'VU', 'VUT', 'Third Country'],
    ['Vatican City', 'VA', 'VAT', 'Third Country'],
    ['Venezuela', 'VE', 'VEN', 'Third Country'],
    ['Virgin Islands (British)', 'VG', 'VGB', 'Third Country'],
    ['Virgin Islands (US)', 'VI', 'VIR', 'Third Country'],
    ['Wallis and Futuna', 'WF', 'WLF', 'Third Country'],
    ['Western Sahara', 'EH', 'ESH', 'Third Country'],
    ['Yemen', 'YE', 'YEM', 'Third Country'],
    ['Zambia', 'ZM', 'ZMB', 'Third Country'],
    ['Zimbabwe', 'ZW', 'ZWE', 'Third Country'],
  ]

  const countries = countriesData.map(([name, isoCode, isoCode3, statusString, description]) => ({
    name,
    isoCode,
    isoCode3,
    gdprStatus: parseGdprStatus(statusString),
    description: description ?? null,
    isActive: true,
  }))

  await prisma.country.createMany({
    data: countries,
    skipDuplicates: true,
  })

  const count = await prisma.country.count()
  console.log(`Seeded ${count} countries`)
  return count
}
